//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parrot_Wings_ASP.NET_Framework_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int id { get; set; }
        public int idRecipient { get; set; }
        public int idAddresser { get; set; }
        public System.DateTime timestamp { get; set; }
        public int amountPW { get; set; }
        public int resultingAddresserBalance { get; set; }
        public int resultingRecipientBalance { get; set; }
    
        public virtual User UserAddresser { get; set; }
        public virtual User UserRecipient { get; set; }
    }
}
